### ISSUE TITLE
Clients stop when receiving unmatched RPC response

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-cpp#17]
If a client receive an RPC response to its former self, it will throw an `RPCError` and log "error in rpc: no function but also no response callback". That seems sensible, but apparantly this can happen and cause a restart loop.

**Comment by phijor** [comment]
Shouldn't we simply discard such a reply as invalid?  Anyone<sup>*me, stupidly*</sup> can issue invalid RPCs and clients really shouldn't crash because of that.  Log a warning and proceed as normal.

**Comment by bmario** [comment]
Probably, the problem is that the manager has a backlog of unprocessed RPC messages. In the meantime, the client disconnects for some reason and reconnects under the same token later. Therefore, a new RPC queue with the same name is created. Once the manager processed the old RPC, the recipient is already gone, but there is a new one under the same name.

Maybe we should think about adding UUIDs to RPC queues or tokens like a session id.

**Comment by bmario** [comment]
One more data point for adding UUID's to RPC queues: https://github.com/metricq/metricq-python/issues/25
